import re


def format_prompt_df(sample : dict) -> dict:
    """
    Formats a single data sample into the Gemma-2 chat template.
        sample : {"business_description" : 'blablabla..', "domain_suggestions" : ['blabla.com', 'bloblo.fr', ..]}
        =>
        "<start_of_turn>user\nGenerate ... <end_of_turn>"
    """
    domains_str = ", ".join(sample['domain_suggestions'])
    
    text = f"<start_of_turn>user\nGenerate a diverse list of high-quality domain names for the following business: {sample['business_description']}<end_of_turn>\n<start_of_turn>model\n{domains_str}<end_of_turn>"
    return {"text": text}


def format_prompt(business_description : str) -> str:
    """
    Same prompt, without the domain names for the training.
    This function is used in inference.py to 'judge' the model's performances.
    """
    prompt = f"<start_of_turn>user\nGenerate a diverse list of high-quality domain names for the following business: {business_description}<end_of_turn>\n<start_of_turn>model\n"

    return prompt


def format_answer_gemma2(suggestion : str) -> list[str]:
    """
    Transforms the suggestion generated by Gemma-2 for the domain name during inference into a list
    of usable domain names.
    Gemma-2 answers using markdown syntax, we need regex to extract relevant answer.
    
    example of answer :
    
    - user
    Generate a diverse list of high-quality domain names for the following business: A sustainable fashion brand that uses recycled ocean plastic.
    model
    ## Sustainable Fashion Domain Names:

    **Short & Catchy:**

    * **OceanChic.com**
    * **PlasticsToFashion.com**
    * **ReThread.com**
    * **EcoThreads.com**
    * **SeaStyle.com**
    * **WaveWear.com**
    * **Re.Made.Fashion.com**
    * **OceanBloom.com**
    * **SeascapeThreads.com**
    """
    # --- Format 1: Bolded domains like **OceanToWear.com:**
    pattern_bold = r'\*\*([^*\n]+?)\*\*'
    matches = re.findall(pattern_bold, suggestion)

    domains = []
    for match in matches:
        domain = match.strip().rstrip(":").rstrip(".")
        if " " in domain:
            continue
        if re.match(r'^\[.*\]$', domain):  # skip placeholders
            continue
        if len(domain) < 4:
            continue
        domains.append(domain)

    if len(domains) > 5:
        return domains

    # --- Format 2: Bullet point domains (non-bolded)
    candidate_lines = re.findall(r'^[*-]\s+(.*)', suggestion, re.MULTILINE)

    for line in candidate_lines:
        candidate = line.strip().split(":")[0].strip().rstrip(".")

        if not candidate or " " in candidate:
            continue
        if re.match(r'^\[.*\]$', candidate):
            continue
        if len(candidate) < 4:
            continue
        if candidate not in domains:
            domains.append(candidate)

    return domains


if __name__ == "__main__":
    test = """user
    Generate a diverse list of high-quality domain names for the following business: A sustainable fashion brand that uses recycled ocean plastic.
    model
    Here's a diverse list of domain names for a sustainable fashion brand using recycled ocean plastic, categorized for your consideration:

    **Descriptive & Clear:**

    * **OceanToWear.com:**  Direct and emphasizes the origin of materials.
    * **PlasticReimagined.com:**  Highlights the brand's innovative approach.
    * **SeaToStyle.com:**  Connects fashion to the ocean and sustainability.
    * **Re.Fashion.Ocean.com:**  Catchy and emphasizes the circularity of the process.
    * **RecycledWaves.com:**  Playful and evokes a sense of movement and change.

    **Catchy & Modern:**

    * **AquaBloom.com:**  Evokes a sense of growth and beauty from recycled materials.
    * **Re.Thread.com:**  Short, memorable, and hints at the material's origin.
    * **OceanVerse.com:**  Modern and suggests a world of sustainable fashion.
    * **SeaShift.com:**  Implies a change in the fashion industry and its impact.
    * **ThePlasticMuse.com:**  Intriguing and connects fashion to a creative force.

    **Unique & Playful:**

    * **WaveWear.com:**  Simple, memorable, and focuses on the ocean's connection.
    * **MermaidThreads.com:**  Whimsical and appeals to a specific audience.
    * **Re.Shore.Style.com:**  


    Business idea: 'A sustainable fashion brand that uses recycled ocean plastic.'"""
    
    print(format_answer_gemma2(test))