import re


def format_prompt_df(sample : dict) -> dict:
    """
    Formats a single data sample into the Gemma-2 chat template.
        sample : {"business_description" : 'blablabla..', "domain_suggestions" : ['blabla.com', 'bloblo.fr', ..]}
        =>
        "<start_of_turn>user\nGenerate ... <end_of_turn>"
    """
    domains_str = ", ".join(sample['domain_suggestions'])
    
    text = f"<start_of_turn>user\nGenerate a diverse list of high-quality domain names for the following business: {sample['business_description']}<end_of_turn>\n<start_of_turn>model\n{domains_str}<end_of_turn>"
    return {"text": text}


def format_prompt(business_description : str) -> str:
    """
    Same prompt, without the domain names for the training.
    This function is used in inference.py to 'judge' the model's performances.
    """
    prompt = f"<start_of_turn>user\nGenerate a diverse list of high-quality domain names for the following business: {business_description}<end_of_turn>\n<start_of_turn>model\n"

    return prompt


def format_answer_gemma2(suggestion : str) -> list[str]:
    """
    Transforms the suggestion generated by Gemma-2 for the domain name during inference into a list
    of usable domain names.
    Gemma-2 answers using markdown syntax, we need regex to extract relevant answer.
    
    example of answer :
    
    - user
    Generate a diverse list of high-quality domain names for the following business: A sustainable fashion brand that uses recycled ocean plastic.
    model
    ## Sustainable Fashion Domain Names:

    **Short & Catchy:**

    * **OceanChic.com**
    * **PlasticsToFashion.com**
    * **ReThread.com**
    * **EcoThreads.com**
    * **SeaStyle.com**
    * **WaveWear.com**
    * **Re.Made.Fashion.com**
    * **OceanBloom.com**
    * **SeascapeThreads.com**
    """
    pattern = r'\*\*(?!.*?:)([^*]+?)\*\*'
    matches = re.findall(pattern, suggestion)

    domains = [match.strip() for match in matches]
    
    return domains


if __name__ == "__main__":
    test = """    - user
    Generate a diverse list of high-quality domain names for the following business: A sustainable fashion brand that uses recycled ocean plastic.
    model
    ## Sustainable Fashion Domain Names:

    **Short & Catchy:**

    * **OceanChic.com**
    * **PlasticsToFashion.com**
    * **ReThread.com**
    * **EcoThreads.com**
    * **SeaStyle.com**
    * **WaveWear.com**
    * **Re.Made.Fashion.com**
    * **OceanBloom.com**
    * **SeascapeThreads.com**

    **Descriptive:**

    * **RecycledOceanFashion.com**
    * **SustainableOceanFashion.com**
    * **OceanPlasticApparel.com**
    * **OceanPlasticsToFashion.com**
    * **EcoFashionFromOcean.com**
    * **ConsciousFashionRemade.com**
    * **OceanPlasticUpcycled.com**

    **Unique & Playful:**

    * **TheOceanistas.com**
    * **ReimaginedWaves.com**
    * **PlasticToPretty.com**
    * **WaveYourStyle.com**
    * **CoralThreads.com**
    * **ReFashionedSea.com**
    * **AquaCouture.com**

    **More Specific:**

    * **SeaToStyle.com** (focus on upcycling and transformation)
    * **OceanReimagined.com** (highlighting innovative design)
    * **ThePlasticFashionist.com** (targeting a specific audience)
    * **RemadeWithOcean.com** (emphas"""
    
    print(format_answer_gemma2(test))